import type { AgentProfile, AppSettings, Repo, TaskSummary } from "./types";

export const demoCreatedAt = "2026-05-15T12:00:00.000Z";

export const demoRepo: Repo = {
  id: 100,
  name: "Nectus Demo",
  path: "/demo/nectus",
  defaultWorktreeRoot: "/demo/nectus-worktrees",
  createdAt: demoCreatedAt,
};

export const demoAgentProfiles: AgentProfile[] = [
  {
    id: 100,
    name: "Codex",
    agentKind: "codex",
    command: "codex",
    model: null,
    args: [],
    env: {},
    createdAt: demoCreatedAt,
    updatedAt: demoCreatedAt,
  },
  {
    id: 101,
    name: "Claude",
    agentKind: "claude",
    command: "claude",
    model: null,
    args: [],
    env: {},
    createdAt: demoCreatedAt,
    updatedAt: demoCreatedAt,
  },
  {
    id: 102,
    name: "Gemini",
    agentKind: "gemini",
    command: "gemini",
    model: null,
    args: [],
    env: {},
    createdAt: demoCreatedAt,
    updatedAt: demoCreatedAt,
  },
];

export const defaultDemoSettings: AppSettings = {
  defaultAgentProfileId: demoAgentProfiles[0].id,
  defaultWorktreeRootPattern: "../{repoName}-worktrees",
  defaultBranchPrefix: null,
  theme: "system",
  density: "comfortable",
  updatedAt: demoCreatedAt,
};

export const demoTasks: TaskSummary[] = [
  {
    id: 1001,
    repoId: demoRepo.id,
    title: "Drag this task into Review",
    prompt: "Drag this task into Review and inspect the board feedback.",
    status: "planned",
    prUrl: null,
    agentProfileId: 100,
    agentName: "Codex",
    agentKind: "codex",
    hasWorktree: true,
    branchName: "demo/drag-task",
    worktreePath: "/demo/nectus-worktrees/demo-drag-task",
    isDirty: false,
    activeSessionId: null,
    lastSessionId: null,
    lastSessionAgent: null,
    lastSessionCwd: null,
    lastSessionLabel: null,
    createdAt: demoCreatedAt,
    updatedAt: demoCreatedAt,
  },
  {
    id: 1002,
    repoId: demoRepo.id,
    title: "Inspect drop target feedback",
    prompt: "Inspect drop target feedback while moving cards between columns.",
    status: "in_progress",
    prUrl: null,
    agentProfileId: 101,
    agentName: "Claude",
    agentKind: "claude",
    hasWorktree: false,
    branchName: null,
    worktreePath: null,
    isDirty: false,
    activeSessionId: null,
    lastSessionId: null,
    lastSessionAgent: null,
    lastSessionCwd: null,
    lastSessionLabel: null,
    createdAt: demoCreatedAt,
    updatedAt: demoCreatedAt,
  },
  {
    id: 1003,
    repoId: demoRepo.id,
    title: "Finished demo task",
    prompt: "Review the completed task state.",
    status: "done",
    prUrl: null,
    agentProfileId: 100,
    agentName: "Codex",
    agentKind: "codex",
    hasWorktree: true,
    branchName: "demo/done-task",
    worktreePath: "/demo/nectus-worktrees/demo-done-task",
    isDirty: true,
    activeSessionId: null,
    lastSessionId: null,
    lastSessionAgent: null,
    lastSessionCwd: null,
    lastSessionLabel: null,
    createdAt: demoCreatedAt,
    updatedAt: demoCreatedAt,
  },
];
